In [1]:
import pandas as pd
import numpy as np

In [2]:
t1 = pd.read_csv('table1.csv')
t2 = pd.read_csv('table2.csv')
t3 = pd.read_csv('table3.csv')
t4 = pd.read_csv('table4.csv')
t5 = pd.read_csv('table5.csv')

In [3]:
#dff = pd.concat([t1,t2,t3,t4,t5])

In [4]:
#dff.to_csv('cws_residents.csv', index = False)

In [5]:
df = pd.read_csv('cws_residents.csv')

In [6]:
pd.options.display.max_columns = None
df.drop(columns=['HMY',"HMYPerson", 'hTenant', 'hTent', 'Rent', 'SRENT'], inplace = True)

In [7]:
df

,HPerson,STOTALAMOUNT,SAmountPaid,BOPEN,HRetentionacct,SNOTES,HProperty,HMY1,SNAME,sStatus,cRent,iTerm,dIncome,GuarantorRequired,TotalIncome,Recommendation,AverageApplicantAge,AvgRiskScore,ReasonThatDroveDecisionDescription
0,3946,5.00,5.00,0,191,Amenity fee (08/2022),136,191,Amenity fee,Approved,1999,2,52500,False,666000,Accept,33,745,Insufficient period of Residence History
1,3946,13.67,13.67,0,112,Water Charge,136,112,Utility-water charges,Approved,1999,2,52500,False,666000,Accept,33,745,Insufficient period of Residence History
2,3946,1311.00,1311.00,0,74,Rent (12/2022),136,74,Rent,Approved,1999,2,52500,False,666000,Accept,33,745,Insufficient period of Residence History
3,3946,13.00,13.00,0,129,Utility-trash charges (10/2021),136,129,Utility-trash charges,Approved,1999,2,52500,False,666000,Accept,33,745,Insufficient period of Residence History
4,3946,42.92,42.92,0,111,Sewer Charge,136,111,Utility-sewer charges,Approved,1999,2,52500,False,666000,Accept,33,745,Insufficient period of Residence History
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
739437,74273,4.17,4.17,0,191,Amenity Fee for 25 days,112,191,Amenity fee,Current,2489,15,4800,False,153816,Accept with Conditions (Max Deposit),37,595,High level of Charge-offs
739438,74273,65.00,65.00,0,134,Non-Refundable Application Fee (Tremendous Joh...,112,134,Application fee,Current,2489,15,4800,False,153816,Accept with Conditions (Max Deposit),37,595,High level of Charge-offs
739439,74273,5.00,5.00,0,186,Convenience Fee (Todre Butler),112,186,OSP resident convenience fee,Current,2489,15,4800,False,153816,Accept with Conditions (Max Deposit),37,595,High level of Charge-offs
739440,74273,2074.17,2074.17,0,74,Rent for 25 days,112,74,Rent,Current,2489,15,4800,False,153816,Accept with Conditions (Max Deposit),37,595,High level of Charge-offs
739441,74273,65.00,65.00,0,134,Non-Refundable Application Fee (Todre Butler),112,134,Application fee,Current,2489,15,4800,False,153816,Accept with Conditions (Max Deposit),37,595,High level of Charge-offs

In [8]:
#Filter by Current status
df_current = df[df['sStatus'] == 'Current']

# Get the indices of users who only have Past status
idx_past = df[~df['HPerson'].isin(df_current['HPerson'])].index

# Filter rows based on past status for users who only have past status
df_past = df.loc[idx_past]

# Combine the current and past dataframes
df_combined = pd.concat([df_current, df_past])

# Sort by HPerson to get the final result
df_final = df_combined.sort_values('HPerson')

In [9]:
df_final

,HPerson,STOTALAMOUNT,SAmountPaid,BOPEN,HRetentionacct,SNOTES,HProperty,HMY1,SNAME,sStatus,cRent,iTerm,dIncome,GuarantorRequired,TotalIncome,Recommendation,AverageApplicantAge,AvgRiskScore,ReasonThatDroveDecisionDescription
1814,3946,1311.00,1311.00,0,74,Rent (06/2022),136,74,Rent,Current,1311,15,52500,False,666000,Accept,33,745,Insufficient period of Residence History
1979,3946,5.00,5.00,0,180,Administration processing fee (05/2022),136,180,Administration processing fee,Current,1311,15,52500,False,666000,Accept,33,745,Insufficient period of Residence History
1980,3946,1311.00,1311.00,0,74,Rent (10/2022),136,74,Rent,Current,1311,15,52500,False,666000,Accept,33,745,Insufficient period of Residence History
1981,3946,5.00,5.00,0,180,Administration processing fee (08/2022),136,180,Administration processing fee,Current,1311,15,52500,False,666000,Accept,33,745,Insufficient period of Residence History
1982,3946,5.00,5.00,0,191,Amenity fee (01/2022),136,191,Amenity fee,Current,1311,15,52500,False,666000,Accept,33,745,Insufficient period of Residence History
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
739431,74273,25.00,25.00,0,129,Utility Trash for 25 days,112,129,Utility-trash charges,Current,2489,15,4800,False,153816,Accept with Conditions (Max Deposit),37,595,High level of Charge-offs
739430,74273,3.33,3.33,0,180,Administration Processing Fee for 25 days,112,180,Administration processing fee,Current,2489,15,4800,False,153816,Accept with Conditions (Max Deposit),37,595,High level of Charge-offs
739440,74273,2074.17,2074.17,0,74,Rent for 25 days,112,74,Rent,Current,2489,15,4800,False,153816,Accept with Conditions (Max Deposit),37,595,High level of Charge-offs
739434,74273,150.00,150.00,0,161,Administrative Fee (Todre Butler),112,161,Administrative fee,Current,2489,15,4800,False,153816,Accept with Conditions (Max Deposit),37,595,High level of Charge-offs
739441,74273,65.00,65.00,0,134,Non-Refundable Application Fee (Todre Butler),112,134,Application fee,Current,2489,15,4800,False,153816,Accept with Conditions (Max Deposit),37,595,High level of Charge-offs

In [10]:
df_final['HPerson'].nunique()

5004

In [11]:
# charge codes: 96, 105, 106, 115, 127, 131, 137, 138,
# 142, 148, 154,155, 156, 163, 166, 169, 183, 189, 192,
# 229, 231, 233, 245, 246, 247, 248, 249,250, 251, 253, 268, 298

In [12]:
charge_codes = [96, 105, 106, 115, 127, 131, 137, 138,142, 148, 154,
                155, 156, 163, 166, 169, 183, 189, 192, 229, 231, 233,
                245, 246, 247, 248, 249,250, 251, 253, 268, 298]

In [13]:
df_final = df_final.reset_index(drop=True)

filtered_df = df_final[df_final['HRetentionacct'].isin(charge_codes)]

In [14]:
filtered_df

,HPerson,STOTALAMOUNT,SAmountPaid,BOPEN,HRetentionacct,SNOTES,HProperty,HMY1,SNAME,sStatus,cRent,iTerm,dIncome,GuarantorRequired,TotalIncome,Recommendation,AverageApplicantAge,AvgRiskScore,ReasonThatDroveDecisionDescription
64,3946,75.00,75.00,0,131,"Uncllctbl key, remote fees",136,131,"Uncllctbl key, remote fees",Current,1311,15,52500,False,666000,Accept,33,745,Insufficient period of Residence History
223,4050,46.17,46.17,0,155,Damage charges - Clean,136,155,Damage charges,Current,1412,12,48000,False,576000,Accept with Conditions (Extra Deposit),33,666,Insufficient period of Residence History
672,5241,25.00,25.00,0,155,Damages- 1 load full of trash left out front t...,137,155,Damage charges,Current,1704,12,5528,False,66336,Accept,23,768,Meets All Property Requirements
717,5242,-21.87,-21.87,0,298,:Write Off Charge Ctrl#45612\r\nWater Charge,137,298,Uncllctbl Non Rent,Current,1676,15,3500,False,85200,Accept with Conditions (Extra Deposit),30,0,No Credit Experience
718,5242,-65.67,-65.67,0,298,:Write Off Charge Ctrl#266780\r\nWater Charge ...,137,298,Uncllctbl Non Rent,Current,1676,15,3500,False,85200,Accept with Conditions (Extra Deposit),30,0,No Credit Experience
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211110,68418,992.34,992.34,0,155,Refund amount held until insurnace claim is pr...,76,155,Damage charges,Current,2069,12,5000,False,134328,Accept,35,678,Limited period of Employment History
215662,69196,40.00,0.87,-1,155,LR Stain Removal - Yellow Stain,87,155,Damage charges,Current,2129,6,0,False,0,A-Meets Requirements,43,0,Meets All Property Requirements
216672,69373,25.00,25.00,0,155,Trash Violation,136,155,Damage charges,Current,2299,13,8000,False,98976,Accept with Conditions (Extra Deposit),24,0,No Credit Experience
225040,71653,107.19,107.19,0,155,patio blind replacement,135,155,Damage charges,Current,1529,15,5200,False,69396,Accept with Conditions (Extra Deposit),23,571,Insufficient period of Employment History
229118,72889,75.00,75.00,0,155,Gate Remote,97,155,Damage charges,Current,1709,8,7500,True,20352,Accept with Conditions (Guarantor),27,757,Insufficient Income to Support Rent

In [15]:
filtered_df['HPerson'].nunique()

191

In [16]:
df_final[df_final['BOPEN'] == -1]

,HPerson,STOTALAMOUNT,SAmountPaid,BOPEN,HRetentionacct,SNOTES,HProperty,HMY1,SNAME,sStatus,cRent,iTerm,dIncome,GuarantorRequired,TotalIncome,Recommendation,AverageApplicantAge,AvgRiskScore,ReasonThatDroveDecisionDescription
188,3962,0.00,0.00,-1,187,Waived Fee - New System,136,187,Waive admin processing fee,Current,1661,12,65000,False,889992,Accept with Conditions (Extra Deposit),27,758,No Credit Experience
190,3962,64.38,0.00,-1,111,Sewer Charge,136,111,Utility-sewer charges,Current,1661,12,65000,False,889992,Accept with Conditions (Extra Deposit),27,758,No Credit Experience
194,3962,17.71,0.00,-1,112,Water Charge,136,112,Utility-water charges,Current,1661,12,65000,False,889992,Accept with Conditions (Extra Deposit),27,758,No Credit Experience
245,4050,0.00,0.00,-1,187,Waived Fee - New System,136,187,Waive admin processing fee,Current,1412,12,48000,False,576000,Accept with Conditions (Extra Deposit),33,666,Insufficient period of Residence History
449,5001,152.76,128.42,-1,111,Sewer Charge,140,111,Utility-sewer charges,Current,2199,13,0,True,54996,Accept with Conditions (Guarantor),23,752,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
231205,74231,1565.10,1444.10,-1,74,Rent for 27 days,83,74,Rent,Current,1739,12,7916,False,94992,Accept,47,770,Meets All Property Requirements
231207,74231,18.00,0.00,-1,129,Utility Trash for 27 days,83,129,Utility-trash charges,Current,1739,12,7916,False,94992,Accept,47,770,Meets All Property Requirements
231212,74273,-65.00,0.00,-1,199,MQ Park Row Transfer,112,199,"Waive application, trnsfr fees",Current,2489,15,4800,False,153816,Accept with Conditions (Max Deposit),37,595,High level of Charge-offs
231213,74273,375.00,95.49,-1,162,Deposit Waiver (Amounts subject to screening r...,112,162,Deposit waiver fee,Current,2489,15,4800,False,153816,Accept with Conditions (Max Deposit),37,595,High level of Charge-offs
231214,74273,-150.00,0.00,-1,211,MQ Park Row Transfer,112,211,Waive administrative fee,Current,2489,15,4800,False,153816,Accept with Conditions (Max Deposit),37,595,High level of Charge-offs