In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('cws_residents.csv')

In [3]:
df = df.drop(columns = ['HMY', 'HMYPerson', 'Rent', 'SRENT', 'hTenant', 'hTent', 'HMY1'])

In [4]:
charge_codes = [96, 105, 106, 115, 127, 131, 137, 138,142, 148, 154,
                155, 156, 163, 166, 169, 183, 189, 192, 229, 231, 233,
                245, 246, 247, 248, 249,250, 251, 253, 268, 298]

In [5]:
df

,HPerson,STOTALAMOUNT,SAmountPaid,BOPEN,HRetentionacct,SNOTES,HProperty,SNAME,sStatus,cRent,iTerm,dIncome,GuarantorRequired,TotalIncome,Recommendation,AverageApplicantAge,AvgRiskScore,ReasonThatDroveDecisionDescription
0,3946,5.00,5.00,0,191,Amenity fee (08/2022),136,Amenity fee,Approved,1999,2,52500,False,666000,Accept,33,745,Insufficient period of Residence History
1,3946,13.67,13.67,0,112,Water Charge,136,Utility-water charges,Approved,1999,2,52500,False,666000,Accept,33,745,Insufficient period of Residence History
2,3946,1311.00,1311.00,0,74,Rent (12/2022),136,Rent,Approved,1999,2,52500,False,666000,Accept,33,745,Insufficient period of Residence History
3,3946,13.00,13.00,0,129,Utility-trash charges (10/2021),136,Utility-trash charges,Approved,1999,2,52500,False,666000,Accept,33,745,Insufficient period of Residence History
4,3946,42.92,42.92,0,111,Sewer Charge,136,Utility-sewer charges,Approved,1999,2,52500,False,666000,Accept,33,745,Insufficient period of Residence History
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
739437,74273,4.17,4.17,0,191,Amenity Fee for 25 days,112,Amenity fee,Current,2489,15,4800,False,153816,Accept with Conditions (Max Deposit),37,595,High level of Charge-offs
739438,74273,65.00,65.00,0,134,Non-Refundable Application Fee (Tremendous Joh...,112,Application fee,Current,2489,15,4800,False,153816,Accept with Conditions (Max Deposit),37,595,High level of Charge-offs
739439,74273,5.00,5.00,0,186,Convenience Fee (Todre Butler),112,OSP resident convenience fee,Current,2489,15,4800,False,153816,Accept with Conditions (Max Deposit),37,595,High level of Charge-offs
739440,74273,2074.17,2074.17,0,74,Rent for 25 days,112,Rent,Current,2489,15,4800,False,153816,Accept with Conditions (Max Deposit),37,595,High level of Charge-offs
739441,74273,65.00,65.00,0,134,Non-Refundable Application Fee (Todre Butler),112,Application fee,Current,2489,15,4800,False,153816,Accept with Conditions (Max Deposit),37,595,High level of Charge-offs

In [6]:
df = df.rename(columns = {'HPerson': 'id',
                   'STOTALAMOUNT': 'total_charges',
                   'SAmountPaid': 'amount_paid',
                   'BOPEN': 'open',
                   'SNOTES': 'description',
                   'HRetentionacct': 'charge_code',
                   'HProperty': 'prop_id',
                   'SNAME':'charge_name',
                   'cRent': 'rent',
                   'iTerm': 'term',
                   'dIncome': 'monthly_inc',
                   'TotalIncome': 'total_inc',
                   'AverageApplicantAge': 'age',
                   'AvgRiskScore':'risk_score',
                   'ReasonThatDroveDecisionDescription': 'reason'})

In [7]:
df

,id,total_charges,amount_paid,open,charge_code,description,prop_id,charge_name,sStatus,rent,term,monthly_inc,GuarantorRequired,total_inc,Recommendation,age,risk_score,reason
0,3946,5.00,5.00,0,191,Amenity fee (08/2022),136,Amenity fee,Approved,1999,2,52500,False,666000,Accept,33,745,Insufficient period of Residence History
1,3946,13.67,13.67,0,112,Water Charge,136,Utility-water charges,Approved,1999,2,52500,False,666000,Accept,33,745,Insufficient period of Residence History
2,3946,1311.00,1311.00,0,74,Rent (12/2022),136,Rent,Approved,1999,2,52500,False,666000,Accept,33,745,Insufficient period of Residence History
3,3946,13.00,13.00,0,129,Utility-trash charges (10/2021),136,Utility-trash charges,Approved,1999,2,52500,False,666000,Accept,33,745,Insufficient period of Residence History
4,3946,42.92,42.92,0,111,Sewer Charge,136,Utility-sewer charges,Approved,1999,2,52500,False,666000,Accept,33,745,Insufficient period of Residence History
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
739437,74273,4.17,4.17,0,191,Amenity Fee for 25 days,112,Amenity fee,Current,2489,15,4800,False,153816,Accept with Conditions (Max Deposit),37,595,High level of Charge-offs
739438,74273,65.00,65.00,0,134,Non-Refundable Application Fee (Tremendous Joh...,112,Application fee,Current,2489,15,4800,False,153816,Accept with Conditions (Max Deposit),37,595,High level of Charge-offs
739439,74273,5.00,5.00,0,186,Convenience Fee (Todre Butler),112,OSP resident convenience fee,Current,2489,15,4800,False,153816,Accept with Conditions (Max Deposit),37,595,High level of Charge-offs
739440,74273,2074.17,2074.17,0,74,Rent for 25 days,112,Rent,Current,2489,15,4800,False,153816,Accept with Conditions (Max Deposit),37,595,High level of Charge-offs
739441,74273,65.00,65.00,0,134,Non-Refundable Application Fee (Todre Butler),112,Application fee,Current,2489,15,4800,False,153816,Accept with Conditions (Max Deposit),37,595,High level of Charge-offs

In [9]:
df = df[df.sStatus == 'Current']

In [11]:
df = df.reset_index(drop=True)

In [18]:
df

,id,total_charges,amount_paid,open,charge_code,description,prop_id,charge_name,sStatus,rent,term,monthly_inc,GuarantorRequired,total_inc,Recommendation,age,risk_score,reason
0,3946,1311.00,1311.00,0,74,Rent (06/2022),136,Rent,Current,1311,15,52500,False,666000,Accept,33,745,Insufficient period of Residence History
1,3946,1311.00,1311.00,0,74,Rent (08/2022),136,Rent,Current,1311,15,52500,False,666000,Accept,33,745,Insufficient period of Residence History
2,3946,1.83,1.83,0,191,Amenity fee (11/2021) 11 days,136,Amenity fee,Current,1311,15,52500,False,666000,Accept,33,745,Insufficient period of Residence History
3,3946,27.00,27.00,0,128,Trash service fee (07/2022),136,Trash service fee,Current,1311,15,52500,False,666000,Accept,33,745,Insufficient period of Residence History
4,3946,21.93,21.93,0,112,Water Charge 01/03/2023 to 02/14/2023 :Final U...,136,Utility-water charges,Current,1311,15,52500,False,666000,Accept,33,745,Insufficient period of Residence History
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
231215,74273,4.17,4.17,0,191,Amenity Fee for 25 days,112,Amenity fee,Current,2489,15,4800,False,153816,Accept with Conditions (Max Deposit),37,595,High level of Charge-offs
231216,74273,65.00,65.00,0,134,Non-Refundable Application Fee (Tremendous Joh...,112,Application fee,Current,2489,15,4800,False,153816,Accept with Conditions (Max Deposit),37,595,High level of Charge-offs
231217,74273,5.00,5.00,0,186,Convenience Fee (Todre Butler),112,OSP resident convenience fee,Current,2489,15,4800,False,153816,Accept with Conditions (Max Deposit),37,595,High level of Charge-offs
231218,74273,2074.17,2074.17,0,74,Rent for 25 days,112,Rent,Current,2489,15,4800,False,153816,Accept with Conditions (Max Deposit),37,595,High level of Charge-offs
231219,74273,65.00,65.00,0,134,Non-Refundable Application Fee (Todre Butler),112,Application fee,Current,2489,15,4800,False,153816,Accept with Conditions (Max Deposit),37,595,High level of Charge-offs