In [1]:
import pandas as pd
import numpy as np
import new_lib as nl

In [2]:
df = pd.read_csv('cws_residents.csv')

In [3]:
df = df.drop(columns = ['HMY', 'HMYPerson', 'Rent', 'SRENT', 'hTenant', 'hTent', 'HMY1'])

In [4]:
charge_codes = [96, 105, 106, 115, 127, 131, 137, 138,142, 148, 154,
                155, 156, 163, 166, 169, 183, 189, 192, 229, 231, 233,
                245, 246, 247, 248, 249,250, 251, 253, 268, 298]

In [5]:
df

,HPerson,STOTALAMOUNT,SAmountPaid,BOPEN,HRetentionacct,SNOTES,HProperty,SNAME,sStatus,cRent,iTerm,dIncome,GuarantorRequired,TotalIncome,Recommendation,AverageApplicantAge,AvgRiskScore,ReasonThatDroveDecisionDescription
0,3946,5.00,5.00,0,191,Amenity fee (08/2022),136,Amenity fee,Approved,1999,2,52500,False,666000,Accept,33,745,Insufficient period of Residence History
1,3946,13.67,13.67,0,112,Water Charge,136,Utility-water charges,Approved,1999,2,52500,False,666000,Accept,33,745,Insufficient period of Residence History
2,3946,1311.00,1311.00,0,74,Rent (12/2022),136,Rent,Approved,1999,2,52500,False,666000,Accept,33,745,Insufficient period of Residence History
3,3946,13.00,13.00,0,129,Utility-trash charges (10/2021),136,Utility-trash charges,Approved,1999,2,52500,False,666000,Accept,33,745,Insufficient period of Residence History
4,3946,42.92,42.92,0,111,Sewer Charge,136,Utility-sewer charges,Approved,1999,2,52500,False,666000,Accept,33,745,Insufficient period of Residence History
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
739437,74273,4.17,4.17,0,191,Amenity Fee for 25 days,112,Amenity fee,Current,2489,15,4800,False,153816,Accept with Conditions (Max Deposit),37,595,High level of Charge-offs
739438,74273,65.00,65.00,0,134,Non-Refundable Application Fee (Tremendous Joh...,112,Application fee,Current,2489,15,4800,False,153816,Accept with Conditions (Max Deposit),37,595,High level of Charge-offs
739439,74273,5.00,5.00,0,186,Convenience Fee (Todre Butler),112,OSP resident convenience fee,Current,2489,15,4800,False,153816,Accept with Conditions (Max Deposit),37,595,High level of Charge-offs
739440,74273,2074.17,2074.17,0,74,Rent for 25 days,112,Rent,Current,2489,15,4800,False,153816,Accept with Conditions (Max Deposit),37,595,High level of Charge-offs
739441,74273,65.00,65.00,0,134,Non-Refundable Application Fee (Todre Butler),112,Application fee,Current,2489,15,4800,False,153816,Accept with Conditions (Max Deposit),37,595,High level of Charge-offs

In [6]:
df = df.rename(columns = {'HPerson': 'id',
                   'STOTALAMOUNT': 'total_charges',
                   'SAmountPaid': 'amount_paid',
                   'BOPEN': 'open',
                   'SNOTES': 'description',
                   'HRetentionacct': 'charge_code',
                   'HProperty': 'prop_id',
                   'SNAME':'charge_name',
                   'cRent': 'rent',
                   'iTerm': 'term',
                   'dIncome': 'monthly_inc',
                   'TotalIncome': 'total_inc',
                   'AverageApplicantAge': 'age',
                   'AvgRiskScore':'risk_score',
                   'ReasonThatDroveDecisionDescription': 'reason'})

In [7]:
df

,id,total_charges,amount_paid,open,charge_code,description,prop_id,charge_name,sStatus,rent,term,monthly_inc,GuarantorRequired,total_inc,Recommendation,age,risk_score,reason
0,3946,5.00,5.00,0,191,Amenity fee (08/2022),136,Amenity fee,Approved,1999,2,52500,False,666000,Accept,33,745,Insufficient period of Residence History
1,3946,13.67,13.67,0,112,Water Charge,136,Utility-water charges,Approved,1999,2,52500,False,666000,Accept,33,745,Insufficient period of Residence History
2,3946,1311.00,1311.00,0,74,Rent (12/2022),136,Rent,Approved,1999,2,52500,False,666000,Accept,33,745,Insufficient period of Residence History
3,3946,13.00,13.00,0,129,Utility-trash charges (10/2021),136,Utility-trash charges,Approved,1999,2,52500,False,666000,Accept,33,745,Insufficient period of Residence History
4,3946,42.92,42.92,0,111,Sewer Charge,136,Utility-sewer charges,Approved,1999,2,52500,False,666000,Accept,33,745,Insufficient period of Residence History
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
739437,74273,4.17,4.17,0,191,Amenity Fee for 25 days,112,Amenity fee,Current,2489,15,4800,False,153816,Accept with Conditions (Max Deposit),37,595,High level of Charge-offs
739438,74273,65.00,65.00,0,134,Non-Refundable Application Fee (Tremendous Joh...,112,Application fee,Current,2489,15,4800,False,153816,Accept with Conditions (Max Deposit),37,595,High level of Charge-offs
739439,74273,5.00,5.00,0,186,Convenience Fee (Todre Butler),112,OSP resident convenience fee,Current,2489,15,4800,False,153816,Accept with Conditions (Max Deposit),37,595,High level of Charge-offs
739440,74273,2074.17,2074.17,0,74,Rent for 25 days,112,Rent,Current,2489,15,4800,False,153816,Accept with Conditions (Max Deposit),37,595,High level of Charge-offs
739441,74273,65.00,65.00,0,134,Non-Refundable Application Fee (Todre Butler),112,Application fee,Current,2489,15,4800,False,153816,Accept with Conditions (Max Deposit),37,595,High level of Charge-offs

In [8]:
df = df[df.sStatus == 'Current']

In [9]:
df = df.reset_index(drop=True)

In [10]:
df.age.unique()

array([ 33,  27,  39,  23,  30,  12,  29,  58,  28,  25,  34,  24,  31,
        43,  22,  20,  35,  57,  40,  45,  38,  46,  54,  41,  21,  47,
        26,  18,  32,  42,  44,  36,  67,  37,  50,  48,  55,  59,  53,
        51,  52,  49,  60,   0,  19,  63,  76,  66,  56,  65,  61,  68,
        78,  64,  69,  62,  79,  80,  74,  71,  72,  88,  77,  73,  85,
        83,  11,  70,  81,  16,   7,  75,  82,  10,  17, 122, 123,   3])

In [11]:
df[df.age == 0]

,id,total_charges,amount_paid,open,charge_code,description,prop_id,charge_name,sStatus,rent,term,monthly_inc,GuarantorRequired,total_inc,Recommendation,age,risk_score,reason
33331,14140,5.00,5.00,0,186,Convenience Fee,133,OSP resident convenience fee,Current,1869,13,4200,True,55200,Accept with Conditions (Guarantor),0,558,Insufficient Income to Support Rent
33332,14140,3.00,3.00,0,190,Next Month's Pest Control,133,Pest control,Current,1869,13,4200,True,55200,Accept with Conditions (Guarantor),0,558,Insufficient Income to Support Rent
33333,14140,1869.00,1869.00,0,74,Rent (09/2022),133,Rent,Current,1869,13,4200,True,55200,Accept with Conditions (Guarantor),0,558,Insufficient Income to Support Rent
33334,14140,3.00,3.00,0,190,Pest control (11/2022),133,Pest control,Current,1869,13,4200,True,55200,Accept with Conditions (Guarantor),0,558,Insufficient Income to Support Rent
33335,14140,25.00,25.00,0,128,Next Month's Valet Trash,133,Trash service fee,Current,1869,13,4200,True,55200,Accept with Conditions (Guarantor),0,558,Insufficient Income to Support Rent
33336,14140,7.00,7.00,0,191,Amenity fee (08/2022),133,Amenity fee,Current,1869,13,4200,True,55200,Accept with Conditions (Guarantor),0,558,Insufficient Income to Support Rent
33337,14140,28.42,28.42,0,116,Electric Usage Charge from 06/29/22 to 07/07/22,133,Utility-electric charges,Current,1869,13,4200,True,55200,Accept with Conditions (Guarantor),0,558,Insufficient Income to Support Rent
33338,14140,4.00,4.00,0,180,Administration processing fee (08/2022),133,Administration processing fee,Current,1869,13,4200,True,55200,Accept with Conditions (Guarantor),0,558,Insufficient Income to Support Rent
33339,14140,3.00,3.00,0,190,Pest control (09/2022),133,Pest control,Current,1869,13,4200,True,55200,Accept with Conditions (Guarantor),0,558,Insufficient Income to Support Rent
33340,14140,1869.00,1869.00,0,74,Rent (11/2022),133,Rent,Current,1869,13,4200,True,55200,Accept with Conditions (Guarantor),0,558,Insufficient Income to Support Rent
33341,14140,1869.00,1869.00,0,74,Rent (08/2022),133,Rent,Current,1869,13,4200,True,55200,Accept with Conditions (Guarantor),0,558,Insufficient Income to Support Rent
33342,14140,7.00,7.00,0,191,Amenity fee (09/2022),133,Amenity fee,Current,1869,13,4200,True,55200,Accept with Conditions (Guarantor),0,558,Insufficient Income to Support Rent
33343,14140,45.88,45.88,0,111,Sewer Charge 10/26/2022 to 12/01/2022 :Final U...,133,Utility-sewer charges,Current,1869,13,4200,True,55200,Accept with Conditions (Guarantor),0,558,Insufficient Income to Support Rent
33344,14140,29.81,29.81,0,111,Sewer Charge :Write Off by Charge Ctrl# 2046918,133,Utility-sewer charges,Current,1869,13,4200,True,55200,Accept with Conditions (Guarantor),0,558,Insufficient Income to Support Rent
33345,14140,175.00,175.00,0,161,Administrative Fee,133,Administrative fee,Current,1869,13,4200,True,55200,Accept with Conditions (Guarantor),0,558,Insufficient Income to Support Rent
33346,14140,-18.13,-18.13,0,298,:Write Off Charge Ctrl#1701465\r\nWater Charge...,133,Uncllctbl Non Rent,Current,1869,13,4200,True,55200,Accept with Conditions (Guarantor),0,558,Insufficient Income to Support Rent
33347,14140,21.07,21.07,0,112,Water Charge,133,Utility-water charges,Current,1869,13,4200,True,55200,Accept with Conditions (Guarantor),0,558,Insufficient Income to Support Rent
33348,14140,25.00,25.00,0,128,Trash service fee (11/2022),133,Trash service fee,Current,1869,13,4200,True,55200,Accept with Conditions (Guarantor),0,558,Insufficient Income to Support Rent
33349,14140,-45.88,-45.88,0,298,:Write Off Charge Ctrl#1701466\r\nSewer Charge...,133,Uncllctbl Non Rent,Current,1869,13,4200,True,55200,Accept with Conditions (Guarantor),0,558,Insufficient Income to Support Rent
33350,14140,11.46,11.46,0,112,Water Charge,133,Utility-water charges,Current,1869,13,4200,True,55200,Accept with Conditions (Guarantor),0,558,Insufficient Income to Support Rent
33351,14140,4.00,4.00,0,180,Administration processing fee (11/2022),133,Administration processing fee,Current,1869,13,4200,True,55200,Accept with Conditions (Guarantor),0,558,Insufficient Income to Support Rent
33352,14140,3.00,3.00,0,190,Pest control (10/2022),133,Pest control,Current,1869,13,4200,True,55200,Accept with Conditions (Guarantor),0,558,Insufficient Income to Support Rent
33353,14140,1869.00,1869.00,0,74,Next Month's Rent,133,Rent,Current,1869,13,4200,True,55200,Accept with Conditions (Guarantor),0,558,Insufficient Income to Support Rent
33354,14140,18.13,18.13,0,112,Water Charge 10/26/2022 to 12/01/2022 :Final U...,133,Utility-water charges,Current,1869,13,4200,True,55200,Accept with Conditions (Guarantor),0,558,Insufficient Income to Support Rent
33355,14140,4.00,4.00,0,180,Next Month's Administration Processing Fee,133,Administration processing fee,Current,1869,13,4200,True,55200,Accept with Conditions (Guarantor),0,558,Insufficient Income to Support Rent
33356,14140,75.00,75.00,0,134,Non-Refundable Application Fee,133,Application fee,Current,1869,13,4200,True,55200,Accept with Conditions (Guarantor),0,558,Insufficient Income to Support Rent
33357,14140,25.00,25.00,0,180,Administration processing fee,133,Administration processing fee,Current,1869,13,4200,True,55200,Accept with Conditions (Guarantor),0,558,Insufficient Income to Support Rent
33358,14140,25.00,25.00,0,128,Trash service fee (10/2022),133,Trash service fee,Current,1869,13,4200,True,55200,Accept with Conditions (Guarantor),0,558,Insufficient Income to Support Rent
33359,14140,11.41,11.41,0,112,Water Charge for 29 Days,133,Utility-water charges,Current,1869,13,4200,True,55200,Accept with Conditions (Guarantor),0,558,Insufficient Income to Support Rent
33360,14140,1.67,1.67,0,128,Valet Trash for 2 days,133,Trash service fee,Current,1869,13,4200,True,55200,Accept with Conditions (Guarantor),0,558,Insufficient Income to Support Rent
33361,14140,-124.60,-124.60,0,92,2 day rent credit for not being able to move in,133,Short term concession,Current,1869,13,4200,True,55200,Accept with Conditions (Guarantor),0,558,Insufficient Income to Support Rent
33362,14140,28.63,28.63,0,111,Sewer Charge for 29 Days,133,Utility-sewer charges,Current,1869,13,4200,True,55200,Accept with Conditions (Guarantor),0,558,Insufficient Income to Support Rent
33363,14140,53.27,53.27,0,111,Sewer Charge,133,Utility-sewer charges,Current,1869,13,4200,True,55200,Accept with Conditions (Guarantor),0,558,Insufficient Income to Support Rent
33364,14140,200.00,200.00,0,136,Late charges,133,Late charges,Current,1869,13,4200,True,55200,Accept with Conditions (Guarantor),0,558,Insufficient Income to Support Rent
33365,14140,50.00,50.00,0,238,Electric Service Charge from 06/29/22 to 07/07/22,133,Utility-vacant recovery fee,Current,1869,13,4200,True,55200,Accept with Conditions (Guarantor),0,558,Insufficient Income to Support Rent
33366,14140,7.00,7.00,0,191,Amenity fee (11/2022),133,Amenity fee,Current,1869,13,4200,True,55200,Accept with Conditions (Guarantor),0,558,Insufficient Income to Support Rent
33367,14140,-29.81,-29.81,0,298,:Write Off Charge Ctrl#1617071\r\nSewer Charge,133,Uncllctbl Non Rent,Current,1869,13,4200,True,55200,Accept with Conditions (Guarantor),0,558,Insufficient Income to Support Rent
33368,14140,28.73,28.73,0,111,Sewer Charge,133,Utility-sewer charges,Current,1869,13,4200,True,55200,Accept with Conditions (Guarantor),0,558,Insufficient Income to Support Rent
33369,14140,11.89,11.89,0,112,Water Charge :Write Off by Charge Ctrl# 2046917,133,Utility-water charges,Current,1869,13,4200,True,55200,Accept with Conditions (Guarantor),0,558,Insufficient Income to Support Rent
33370,14140,4.00,4.00,0,180,Administration processing fee (09/2022),133,Administration processing fee,Current,1869,13,4200,True,55200,Accept with Conditions (Guarantor),0,558,Insufficient Income to Support Rent
33371,14140,-11.89,-11.89,0,298,:Write Off Charge Ctrl#1617070\r\nWater Charge,133,Uncllctbl Non Rent,Current,1869,13,4200,True,55200,Accept with Conditions (Guarantor),0,558,Insufficient Income to Support Rent
33372,14140,4.00,4.00,0,180,Administration processing fee (10/2022),133,Administration processing fee,Current,1869,13,4200,True,55200,Accept with Conditions (Guarantor),0,558,Insufficient Income to Support Rent
33373,14140,124.60,124.60,0,74,Rent for 2 days,133,Rent,Current,1869,13,4200,True,55200,Accept with Conditions (Guarantor),0,558,Insufficient Income to Support Rent
33374,14140,0.47,0.47,0,191,Amenity Fee for 2 days,133,Amenity fee,Current,1869,13,4200,True,55200,Accept with Conditions (Guarantor),0,558,Insufficient Income to Support Rent
33375,14140,25.00,25.00,0,128,Trash service fee (08/2022),133,Trash service fee,Current,1869,13,4200,True,55200,Accept with Conditions (Guarantor),0,558,Insufficient Income to Support Rent
33376,14140,0.20,0.20,0,190,Pest Control for 2 days,133,Pest control,Current,1869,13,4200,True,55200,Accept with Conditions (Guarantor),0,558,Insufficient Income to Support Rent
33377,14140,7.00,7.00,0,191,Amenity fee (10/2022),133,Amenity fee,Current,1869,13,4200,True,55200,Accept with Conditions (Guarantor),0,558,Insufficient Income to Support Rent
33378,14140,1869.00,1869.00,0,74,Rent (10/2022),133,Rent,Current,1869,13,4200,True,55200,Accept with Conditions (Guarantor),0,558,Insufficient Income to Support Rent
33379,14140,3.00,3.00,0,190,Pest control (08/2022),133,Pest control,Current,1869,13,4200,True,55200,Accept with Conditions (Guarantor),0,558,Insufficient Income to Support Rent
33380,14140,7.00,7.00,0,191,Next Month's Amenity Fee,133,Amenity fee,Current,1869,13,4200,True,55200,Accept with Conditions (Guarantor),0,558,Insufficient Income to Support Rent
33381,14140,25.00,25.00,0,128,Trash service fee (09/2022),133,Trash service fee,Current,1869,13,4200,True,55200,Accept with Conditions (Guarantor),0,558,Insufficient Income to Support Rent
33382,14140,0.27,0.27,0,180,Administration Processing Fee for 2 days,133,Administration processing fee,Current,1869,13,4200,True,55200,Accept with Conditions (Guarantor),0,558,Insufficient Income to Support Rent

In [12]:
df['bad_resident'] = df['charge_code'].isin(charge_codes)

In [13]:
df['bad_resident'] = np.where(df.bad_resident == True, 1, 0)

In [14]:
df[df['bad_resident'] == 1].groupby(by=id)

In [15]:
df.groupby(by = id)

In [16]:
df = df.drop_duplicates(subset = ['id', 'bad_resident'])

In [17]:

df[df['charge_code'] == 298].description

713       :Write Off Charge Ctrl#266779\r\nSewer Base Ch...
1357      :Write Off Charge Ctrl#51192\r\nAdministration...
1507      :Write Off Charge Ctrl#277078\r\nWater Base Ch...
1648                       :Write Off Charge Ctrl#80344\r\n
1825         :Write Off Charge Ctrl#1235546\r\nSewer Charge
                                ...
167535    :Write Off Charge Ctrl#2052975\r\nUtility-wate...
169891                               Water/sewer do not owe
182356    :Write Off Charge Ctrl#2259319\r\nSewer Charge...
193862    :Write Off Charge Ctrl#2284869\r\nWater Charge...
195116    :Write Off Charge Ctrl#2284874\r\nSewer Charge...
Name: description, Length: 62, dtype: object

In [18]:
df[df['bad_resident'] == 1]

,id,total_charges,amount_paid,open,charge_code,description,prop_id,charge_name,sStatus,rent,term,monthly_inc,GuarantorRequired,total_inc,Recommendation,age,risk_score,reason,bad_resident
119,3946,75.00,75.00,0,131,"Uncllctbl key, remote fees",136,"Uncllctbl key, remote fees",Current,1311,15,52500,False,666000,Accept,33,745,Insufficient period of Residence History,1
282,4050,46.17,46.17,0,155,Damage charges - Clean,136,Damage charges,Current,1412,12,48000,False,576000,Accept with Conditions (Extra Deposit),33,666,Insufficient period of Residence History,1
691,5241,25.00,25.00,0,155,Damages- 1 load full of trash left out front t...,137,Damage charges,Current,1704,12,5528,False,66336,Accept,23,768,Meets All Property Requirements,1
713,5242,-4.25,-4.25,0,298,:Write Off Charge Ctrl#266779\r\nSewer Base Ch...,137,Uncllctbl Non Rent,Current,1676,15,3500,False,85200,Accept with Conditions (Extra Deposit),30,0,No Credit Experience,1
889,5246,-5.00,-5.00,0,192,:Write Off Charge Ctrl#28322\r\nAmenity fee (1...,140,Uncllctbl amenity fee,Current,1706,15,3600,False,98304,Accept,12,607,Insufficient period of Employment History,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211087,68418,992.34,992.34,0,155,Refund amount held until insurnace claim is pr...,76,Damage charges,Current,2069,12,5000,False,134328,Accept,35,678,Limited period of Employment History,1
215644,69196,40.00,0.87,-1,155,LR Stain Removal - Yellow Stain,87,Damage charges,Current,2129,6,0,False,0,A-Meets Requirements,43,0,Meets All Property Requirements,1
216687,69373,25.00,25.00,0,155,Trash Violation,136,Damage charges,Current,2299,13,8000,False,98976,Accept with Conditions (Extra Deposit),24,0,No Credit Experience,1
225051,71653,107.19,107.19,0,155,patio blind replacement,135,Damage charges,Current,1529,15,5200,False,69396,Accept with Conditions (Extra Deposit),23,571,Insufficient period of Employment History,1
229125,72889,75.00,75.00,0,155,Gate Remote,97,Damage charges,Current,1709,8,7500,True,20352,Accept with Conditions (Guarantor),27,757,Insufficient Income to Support Rent,1

In [19]:
df.groupby(["id", "bad_resident"])['id'].count()

id     bad_resident
3946   0               1
       1               1
3962   0               1
4050   0               1
       1               1
                      ..
74033  0               1
74056  0               1
74230  0               1
74231  0               1
74273  0               1
Name: id, Length: 5195, dtype: int64

In [20]:
#Filter by bad resident
df_bad = df[df['bad_resident'] == 1]

# Get the indices of users who only have 0 status
idx_0 = df[~df['id'].isin(df_bad['id'])].index

# Filter rows based on 0 status for users who only have 0 status
df_0 = df.loc[idx_0]

# Combine the 1 and 0 dataframes
df_combined = pd.concat([df_bad, df_0])

# Sort by id to get the final result
df = df_combined.sort_values('id')

In [21]:
df = df.sample(frac=1).reset_index(drop = True)

In [23]:
train, validate, test, X_train, y_train, X_val, y_val, X_test, y_test = nl.train_vailidate_test_split(df, 'bad_resident', 'bad_resident')

In [26]:
train[train.bad_resident == 1]

,id,total_charges,amount_paid,open,charge_code,description,prop_id,charge_name,sStatus,rent,term,monthly_inc,GuarantorRequired,total_inc,Recommendation,age,risk_score,reason,bad_resident
2886,6392,75.00,75.00,0,131,Key Fob,136,"Uncllctbl key, remote fees",Current,1409,12,4000,False,148968,Accept,39,660,Moderate level of late credit payments,1
3502,21618,50.00,0.00,-1,154,Heavy trash out,134,Charges for cleaning needed,Current,1409,12,1560,True,18720,Accept with Conditions (Guarantor),26,565,Insufficient Income to Support Rent,1
837,5415,-70.77,-70.77,0,298,:Write Off Charge Ctrl#1036387\r\nSewer Charge...,137,Uncllctbl Non Rent,Current,1606,12,0,True,0,Accept with Conditions (Guarantor),20,710,Insufficient Income to Support Rent,1
4848,6462,75.00,75.00,0,131,Key Fob,136,"Uncllctbl key, remote fees",Current,1649,12,3919,False,84936,Accept,32,739,Meets All Property Requirements,1
480,6364,200.00,200.00,0,155,Damages replace and hang bedroom door,140,Damage charges,Current,2079,10,12916,False,154992,Accept with Conditions (Extra Deposit),38,731,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4281,6135,-6.06,-6.06,0,298,:Write Off Charge Ctrl#447761\r\n,136,Uncllctbl Non Rent,Current,1433,12,7500,False,155220,REJECT,33,649,Severe level of Charge-offs,1
2108,5250,-416.75,-416.75,0,105,:Write Off Charge Ctrl#1036499\r\nRent - pro r...,137,Uncllctbl rent,Current,1696,12,9895,False,168780,Accept,29,668,Insufficient period of Employment History,1
1583,33491,-50.00,-50.00,0,298,:Write Off Charge Ctrl#434937\r\nNon-Refundabl...,95,Uncllctbl Non Rent,Current,1399,13,5280,False,63360,Accept with Conditions (Extra Deposit),28,0,No Credit Experience,1
3799,31565,50.00,50.00,0,155,patio violation - 2nd notice,73,Damage charges,Current,1479,15,6700,False,84900,Accept with Conditions (Extra Deposit),26,0,No Credit Experience,1
3182,6459,75.00,75.00,0,131,Key Fob,136,"Uncllctbl key, remote fees",Current,1509,15,5200,False,82848,REJECT,27,553,Severe level of Charge-offs,1